jobs:
  - job: 'Linux'
    strategy:
      matrix:
        shared:
          xsql_use_shared_xeus: 1
          xsql_use_shared_xeus_sql: 1
        static:
          xsql_use_shared_xeus: 0
          xsql_use_shared_xeus_sql: 0
    pool:
      vmImage: ubuntu-20.04
    timeoutInMinutes: 30
    steps:
          
      - bash: echo "##vso[task.prependpath]$CONDA/bin"
        displayName: Add conda to PATH

      - template: unix-build.yml
        parameters:
          platform: 'Linux'
